// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agsmozmjupxlshrgoygt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnc21vem1qdXB4bHNocmdveWd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MTI2MDgsImV4cCI6MjA2MjE4ODYwOH0.fvpn_6dJiw4t8gUo0yhRcsY7DKPvYGl1zD0KSZpuVsw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);